urls.py
from django.conf.urls import url
from .views import SelectDossier, savegh, saveghrepet, saveinstrugh, creerdossier, listedossiers, \
                    gh_csv, ghquestions_pdf, gh_resultats_tous, fait_entete_spss, fait_entete_stata, exportstatsgh, \
                    gh_res_repet_tous, gh_decrypte_personne
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', SelectDossier, name='SelectDossier'),
    url(r'^savegh/(?P<qid>[-\w]+)/(?P<intid>[-\w]+)/(?P<pid>[-\w]+)/$', savegh, name='savegh'),
    url(r'^saveghrepet/(?P<qid>[-\w]+)/(?P<intid>[-\w]+)/(?P<pid>[-\w]+)/$', saveghrepet, name='saveghrepet'),
    url(r'^saveinstrugh/(?P<intid>[-\w]+)/(?P<pid>[-\w]+)/$', saveinstrugh, name='saveinstrugh'),
    url(r'^new/$', creerdossier, name='creerdossier'),
    url(r'^liste/(?P<province>[-\w]+)/$', listedossiers, name='listedossiers'),
    url(r'^txt/(?P<pid>[-\w]+)', gh_csv, name='gh_csv'),
    url(r'^datas/(?P<qid>[-\w]+)/(?P<intid>[-\w]+)/$', gh_resultats_tous, name='gh_csv_tous'),
    url(r'^SPSSsyntax/(?P<qid>[-\w]+)/(?P<intid>[-\w]+)/$', fait_entete_spss, name='fait_entete_spss'),
    url(r'^STATAsyntax/(?P<qid>[-\w]+)/(?P<intid>[-\w]+)/$', fait_entete_stata, name='fait_entete_stata'),
    url(r'^exportstats/$', exportstatsgh, name='exportstatsgh'),
    url(r'^datasrepet/(?P<qid>[-\w]+)/$', gh_res_repet_tous, name='gh_res_repet_tous'),
    url(r'^decrypte/$', gh_decrypte_personne, name='gh_decrypte_personne'),
    url(r'^pdf/(?P<pk>[-\w]+)/(?P<intid>[-\w]+)/$', ghquestions_pdf, name='dogh_questions_pdf'),
]

models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models



#listes valeurs dependant de province
DEFAULT_PID = 1
class Province(models.Model):
    nom_en = models.CharField(max_length=200, )
    nom_fr = models.CharField(max_length=200, )
    reponse_en = models.CharField(max_length=200, )
    reponse_fr = models.CharField(max_length=200, )
    reponse_valeur = models.IntegerField()

    def __str__(self):
        return '%s' % self.reponse_en


class Etablissement(models.Model):
    reponse_valeur = models.CharField(max_length=200)
    reponse_en = models.CharField(max_length=200, )
    reponse_fr = models.CharField(max_length=200, )
    province = models.ForeignKey(Province, default=DEFAULT_PID, on_delete=models.DO_NOTHING)

    class Meta:
        ordering = ['reponse_valeur']

    def __str__(self):
        return '%s' % self.reponse_en


##############
#Indispensable au questionnaire
class Typequestion(models.Model):
    nom = models.CharField(max_length=200, )
    tatable = models.CharField(max_length=200, blank=True, null=True)
    taille = models.CharField(max_length=200, )

    def __str__(self):
        return '%s' % self.nom


class Victime(models.Model):
    # a part a cause du tri par id du a la hierarchie des reponses proposees
    reponse_valeur = models.CharField(max_length=200)
    reponse_en = models.CharField(max_length=200, )
    reponse_fr = models.CharField(max_length=200, )

    class Meta:
        ordering = ['id']

    def __str__(self):
        return '%s' % self.reponse_en


#listes valeurs SANS province
class Listevaleur(models.Model):
    reponse_valeur = models.CharField(max_length=200)
    reponse_en = models.CharField(max_length=200, )
    reponse_fr = models.CharField(max_length=200, )
    typequestion = models.ForeignKey(Typequestion, on_delete=models.DO_NOTHING)

    class Meta:
        ordering = ['typequestion', 'reponse_valeur']

    def __str__(self):
        return '%s' % self.reponse_en


class Questionnaire(models.Model):
    nom_en = models.CharField(max_length=200, )
    nom_fr = models.CharField(max_length=200, )
    description = models.CharField(max_length=200, )

    def __str__(self):
        return '%s' % self.nom_en


class Interview(models.Model):
    reponse_valeur = models.CharField(max_length=200, )
    reponse_en = models.CharField(max_length=200, )
    reponse_fr = models.CharField(max_length=200, )

    def __str__(self):
        return '%s' % self.reponse_en


##############
class Question(models.Model):
    questionno = models.IntegerField()
    questionen = models.CharField(max_length=255,)
    questionfr = models.CharField(max_length=255,)
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.DO_NOTHING)
    typequestion = models.ForeignKey(Typequestion, on_delete=models.DO_NOTHING)
    parent= models.ForeignKey("self",default=1, on_delete=models.DO_NOTHING)
    relation = models.CharField(blank=True, null=True, max_length=45,)
    cible = models.CharField(blank=True, null=True, max_length=45,)
    varname = models.CharField(blank=True, null=True, max_length=45,)
    aidefr = models.TextField(blank=True, null=True)
    aideen = models.TextField(blank=True, null=True)
    qstyle = models.CharField(blank=True, null=True, max_length=45,)
    phase = models.CharField(blank=True, null=True, max_length=45,)
    parentvarname = models.CharField(blank=True, null=True, max_length=45,)

    class Meta:
        ordering = ['questionnaire', 'questionno']

    def __str__(self):
        return '%s' % self.questionen


#########################
class Instrument(models.Model):
    #Pour identifier les instruments
    nom = models.ForeignKey(Question, related_name='questionsinstrument', on_delete=models.CASCADE)
    phase = models.CharField(blank=True, null=True, max_length=45, )


class ItemInstrument(models.Model):
    #Pour identifier les items des instruments
    instrument = models.ForeignKey(Instrument, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)


class QuestionItem(models.Model):
    #Pour trouver les réponses aux questions reliees aux items des instruments
    item = models.ForeignKey(ItemInstrument, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)


###########
class Reponse(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    reponse_no = models.CharField(max_length=200)
    reponse_valeur = models.CharField(max_length=200)
    reponse_en = models.CharField(max_length=200,)
    reponse_fr = models.CharField(max_length=200,)
    questionnaire = models.CharField(blank=True, null=True, max_length=45, )

    class Meta:
        ordering = ['reponse_valeur']

    def __str__(self):
        return '%s' % self.reponse_en


class Personne(models.Model):
    personne_code = models.CharField(max_length=200,)
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    date_consentement = models.CharField(max_length=200,blank=True, null=True)
    PartN = models.TextField()                                              #encrypte
    PartP = models.CharField(max_length=200,)
    VerdictDate = models.TextField(blank=True, null=True)
    LibeDate = models.TextField(blank=True, null=True)
    DDN = models.TextField(blank=True, null=True)                           #encrypte
    Consent = models.IntegerField()
    ConsentAudio = models.IntegerField()
    ConsentFamille = models.IntegerField()
    ConsentSuivi = models.IntegerField()
    fpsyn = models.IntegerField(blank=True, null=True)
    fps = models.TextField(max_length=200,blank=True, null=True)            #encrypte
    Medicyn = models.IntegerField(blank=True, null=True)
    Medic = models.TextField(blank=True, null=True)                         #encrypte
    Hearingdate = models.CharField(max_length=200,blank=True, null=True)
    confid1 = models.TextField(blank=True, null=True)                       #encrypte
    confid2 = models.TextField(blank=True, null=True)                       #encrypte
    assistant = models.ForeignKey(User, related_name='assistant2gh', on_delete=models.DO_NOTHING)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s' % self.personne_code


class Resultat(models.Model):
    personne = models.ForeignKey(Personne, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    reponse_texte = models.TextField(blank=True, null=True)
    reponse_code = models.CharField(max_length=10, blank=True, null=True)
    assistant = models.ForeignKey(User, related_name='assistantgh', on_delete=models.DO_NOTHING)
    interview = models.ForeignKey(Interview, on_delete=models.CASCADE)
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('personne', 'question', 'interview', 'assistant'),)

    def __str__(self):
        return '%s' % self.reponse_texte


#Pour housing et jobs repetitive (questionnaire 4 Work TLBF et 3 Housing TLFB
class Resultatrepet(models.Model):
    personne = models.ForeignKey(Personne, on_delete=models.DO_NOTHING)
    question = models.ForeignKey(Question, db_index=True, on_delete=models.DO_NOTHING)
    questionnaire =  models.ForeignKey(Questionnaire,db_index=True, on_delete=models.DO_NOTHING)
    reponsetexte = models.CharField(max_length=200, blank=True, null=True)
    assistant = models.ForeignKey(User, related_name='arrepetgh', on_delete=models.DO_NOTHING)
    interview = models.ForeignKey(Interview, on_delete=models.DO_NOTHING)
    province = models.ForeignKey(Province, on_delete=models.DO_NOTHING)
    fiche = models.IntegerField(db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('personne','questionnaire', 'question', 'interview', 'fiche', 'assistant'))

        ordering = ['personne','questionnaire', 'question', 'interview', 'fiche', 'assistant']

    def __str__(self):
        return '%s' % self.reponsetexte

templates/choixgh.html
{% load i18n %}
{% load static %}

<html>
    <head>
        <title>Going Home -  Data entry</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'accueil/w3.css' %}">
        <link rel="stylesheet" href="{% static 'gh/w3taupe.css' %}">
        <script type="text/javascript" src="/static/jquery.js"></script>
        <script type="text/javascript" src="/static/tabber.js"></script>
        <link rel="stylesheet" type="text/css" href="/static/sondageM.css" />

    </head>
<body class="w3-theme-l4">

<header class="w3-row w3-theme-d3" id="myHeader">
    <div class="w3-quarter">
        <a href="{% url 'logout' %}" class="w3-button w3-theme-action"> Logout</a>
    </div>

    <div class="w3-half w3-center">
        <h4>Going Home -  Data entry</h4>
    </div>
    <div class="w3-quarter w3-right-align">
    </div>
</header>
<div class="principal">

{% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
{% endif %}
<h2>{{ user.first_name }} {{ user.last_name }} </h2>

   <div class="tabber">
       <div class="tabbertab">
           <form method="post" action="">
               {% csrf_token %}
               <h3>File creation</h3><b>To create a new file you need to have these infos:</b>
                <p>
                   <ul>
                   <li>Name and first name</li>
                   <li>date of verdict</li>
                   <li>date of release from hospital</li>
                   <li>date of consent</li>
                    </ul>
                    </p>
                   <button type="submit" class="placeboutons" name="Newfile">New File</button></td></tr>
                </table>
            </form>
       </div>
       <div class="tabbertab">
           <form method="post" action="">
           {% csrf_token %}
           <h3>Already created file</h3><b>For already created files</b>
               <p>To continue an evaluation once the file is already created</p>
               <table>
                <tr><td></td><td></td></tr>
                <tr><td>Personne</td><td><select name="personneid" >
                    <option value="">Select a case</option>
                    {% for personne in personnes %}
                    <option value="{{personne.id }}">{{ personne.personne_code }}</option>
                    {% endfor %}
                    </select></td></tr>
                <tr><td>Interview</td><td><select name="interviewid" >
                    <option value="">Select an interview</option>
                    {% for interview in interviews %}
                    <option value="{{interview.id }}">{{ interview.reponse_en }}</option>
                    {% endfor %}
                    </select></td></tr>
                <tr><td>Infos from clinical file (baseline only)</td><td><button type="submit" class="placeboutons" name="Clinical File">Clinical File</button></td></tr>
                <tr><td>Socio demo, Relationship, Work Finances, Family friends</td><td><button type="submit" class="placeboutons" name="Interview Guide 1">Interview Guide 1</button></td></tr>
                <tr><td>Antisocial, Alcohol, Drugs, Treatments' Stress, Leisure, Goals</td><td><button type="submit" class="placeboutons" name="Interview Guide 2">Interview Guide 2</button></td></tr>
                <tr><td>Baseline VRAG, SCID Alcohol/Drug, SCID APD; All interviews HCR-20-V3, START</td><td><button type="submit" class="placeboutons" name="Instruments">Instruments</button></td></tr>
                <tr><td>All interviews RAS, CSI, General Impression; Followup only: SOS</td><td><button type="submit" class="placeboutons" name="Scales">Scales</button></td></tr>
                <tr><td>Sensible data (FPS, DOB ...) which will be encrypted</td><td><button type="submit" class="placeboutons" name="Sensible">Sensible data</button></td></tr>
                <tr><td>To see saved data in tabular form</td><td><button type="submit" class="placeboutons" name="PrintFile">Export case to csv</button></td></tr>
               </table>
           </form>
       </div>
       <div class="tabbertab">
        <h3>TLBF Work Housing FUI</h3>
            <form method="post" action="">
                {% csrf_token %}
               <table>
                <tr><td></td><td></td></tr>
                <tr><td>Personne</td><td><select name="personneid" >
                    <option value="">Select a case</option>
                    {% for personne in personnes %}
                    <option value="{{personne.id }}">{{ personne.personne_code }}</option>
                    {% endfor %}
                    </select></td></tr>
                <tr><td>Interview</td><td><select name="interviewid" >
                    <option value="">Select an interview</option>
                    {% for interview in interviews %} {% if interview.id > 1 %}
                        <option value="{{ interview.id }}">{{ interview.reponse_en }}</option>
                    {% endif %}{% endfor %}
                    </select></td></tr>
                 <tr><td>Work TLFB - Follow up interviews only</td><td><button type="submit" class="placeboutons" name="WorkTLBF">Work TLBF</button></td></tr>
                 <tr><td>Housing TLFB - Follow up interviews only</td><td><button type="submit" class="placeboutons" name="HousingTLFB">Housing TLFB</button></td></tr>
               </table>
            </form>
       </div>
       <div class="tabbertab">
           <form method="post" action="">
           {% csrf_token %}
               <h3>To see list of files with the interview dates</h3>
                <table>
                <tr><td></td><td></td></tr>
                <tr><td>Province</td><td><select name="provinceid" >
                    <option value="">Select a province</option>
                    {% for p in provinces %}
                    {% if p.reponse_valeur < 4 %}
                    <option value="{{p.reponse_valeur }}">{{ p.nom_en }}</option>
                    {% endif %}
                    {% endfor %}
                    </select></td></tr>
                <tr><td>See list of files with interview date and status</td><td><button type="submit" class="placeboutons" name="Voirliste">See list</button></td></tr>
                </table>
           </form>
       </div>
       <div class="tabbertab">
        <h3>To print variable list and dictionnary</h3>
            <table>
                <tr class="w3-theme-d1"><td><b>Baseline</b></td><td></td></tr>
                <tr><td>Infos from clinical file (baseline only)</td><td><a href="{% url 'dogh_questions_pdf' 200 1 %}" class= 'button'><b> >> Clinical file Do pdf</b></a></td></tr>
                <tr><td>Socio demo, Relationship, Work Finances, Family friends</td><td><a href="{% url 'dogh_questions_pdf' 10 1 %}" class= 'button'><b> >> Interview Guide 1 Do pdf</b></a></td></tr>
                <tr><td>Antisocial, Alcohol, Drugs, Treatments' Stress, Leisure, Goals</td><td><a href="{% url 'dogh_questions_pdf' 15 1 %}" class= 'button'><b> >> Interview Guide 2 Do pdf</b></a></td></tr>
                <tr><td>Baseline VRAG, SCID Alcohol/Drug, SCID APD; All interviews HCR-20-V3, START</td><td><a href="{% url 'dogh_questions_pdf' 100 1 %}" class= 'button'><b> >> Instruments Do pdf</b></a></td></tr>
                <tr><td>All interviews RAS, CSI, General Impression</td><td><a href="{% url 'dogh_questions_pdf' 101 1 %}" class= 'button'><b> >> Scales Do pdf</b></a></td></tr>
                <tr class="w3-theme-d1"><td><b>Followup</b></td><td></td></tr>
                <tr><td>Socio demo, Relationship, Work Finances, Family friends</td><td><a href="{% url 'dogh_questions_pdf' 10 2 %}" class= 'button'><b> >> Interview Guide 1 FU Do pdf</b></a></td></tr>
                <tr><td>Antisocial, Alcohol, Drugs, Treatments' Stress, Leisure, Goals</td><td><a href="{% url 'dogh_questions_pdf' 15 2 %}" class= 'button'><b> >> Interview Guide 2 FU Do pdf</b></a></td></tr>
                <tr><td>HCR-20-V3, START</td><td><a href="{% url 'dogh_questions_pdf' 100 2 %}" class= 'button'><b> >> Instruments FU Do pdf</b></a></td></tr>
                <tr><td>RAS, CSI, General Impression; Followup only: SOS</td><td><a href="{% url 'dogh_questions_pdf' 101 2 %}" class= 'button'><b> >> Scales FU Do pdf</b></a></td></tr>
                <tr><td>Work TLFB</td><td><a href="{% url 'dogh_questions_pdf' 4 2 %}" class= 'button'><b> >> Work (one card for each job) Do pdf</b></a></td></tr>
                <tr><td>Housing TLFB</td><td><a href="{% url 'dogh_questions_pdf' 3 2 %}" class= 'button'><b> >> Housing (one card for each address) Do pdf</b></a></td></tr>
                <tr class="w3-theme-d1"><td><b>Family</b></td><td></td></tr>
                <tr><td>Family interview Baseline</td><td><a href="{% url 'dogh_questions_pdf' 600 1 %}" class= 'button'><b> >> Family Baseline Do pdf</b></a></td></tr>
                <tr><td>Family Interview Follow Up</td><td><a href="{% url 'dogh_questions_pdf' 600 2 %}" class= 'button'><b> >> Family Follow Up Do pdf</b></a></td></tr>
            </table>
        </div>
   </div>
</div>
<footer class="w3-container w3-theme-d5 footerw3">
    <h5><a class="w3-text-white" href="mailto:malijai.caulet.ippm@ssss.gouv.qc.ca?subject=Going Home troubles">For any question or problem : contact</a></h5>
</footer>

</body>
</html>

templates/createghh.html
{% extends 'gh_base.html' %}
{% load i18n %}
{% load static %}
{% load formulairesgh %}

{% block content %}
<h2>New file creation: 
Be carefull all these data will not be accessible after saving</h2>
{% csrf_token %}
   <div class="tabber">
    {% for question in questions %}
        {% if question.typequestion.nom == 'TITLE' %}
            {% if forloop.counter > 1 %}
                </table></div>
            {% endif %}
                 <div class="tabbertab"><h3>{{ question.questionen|slice:"0:15" }}</h3><b>{{ question.questionen}}</b>
                 <table><tr><td></td><td></td><td></td></tr>
        {% else %}
            <tr class="{% cycle 'Q1' 'Q2' %}">
                {% include "gh_snippetcreate.html" with typequest=question.typequestion textequest=question.questionen questid=question.id province=user.profile.province varname=question.varname %}
                {% include "aidegh_snippet.html" with aide=question.aideen %}
            </tr>

        {% endif %}
    {% endfor %}
</table>

</div><!--Fermeture de la boite à onglets-->
{% endblock content %}

templates/dateghrepet_snippet.html
{% load formulairesghrepet %}
{% autoescape off %}
{% fait_dateghrep persid=pid province=user.profile.province uid=user.id interview=intid ordre=x qid=qid %}
{% endautoescape %}

templates/savegh.html
{% extends 'gh_base.html' %}
{% load i18n %}
{% load static %}
{% load formulairesgh %}

{% block content %}
<h2>{{Questtitre}}</h2>
<h2> {{ code }} - {{ questionnaire }} - {{ interview }}</h2>
{% csrf_token %}
   <input name="qid" type="hidden" value="{{ qid }}" />
   <input name="intid" type="hidden" value="{{ intid }}" />
    <p class="termine">{% include "gh_snippet.html" with typequest=questionfin.typequestion textequest=questionfin.questionen questid=questionfin.id persid=pid province=user.profile.province varname=questionfin.varname intid=intid %}</p>
   <div class="tabber">

    {% for question in questions %}
        {% if question.typequestion.nom == 'TITLE' %}
            {% if forloop.counter > 1 %}
                </table></div>
            {% endif %}
                 <div class="tabbertab"><h3>{{ question.questionen|slice:"0:15" }}</h3><b>{{ question.questionen}}</b>
                 <table><tr><td></td><td></td><td></td></tr>
        {% elif question.typequestion.nom == 'COMMENT' %}
            <tr><td class="plusdeux" colspan="3">{{ question.questionen }}<td></tr>
        {% else %}
            {% if question.id not in ascendancesF and question.id not in ascendancesM %}
                <tr class="{% cycle 'Q1' 'Q2' %}">
                    {% include "gh_snippet.html" with typequest=question.typequestion textequest=question.questionen questid=question.id persid=pid province=user.profile.province varname=question.varname intid=intid %}
                    {% include "aidegh_snippet.html" with aide=question.aideen %}
                </tr>
            {% elif question.id in ascendancesF and question.id in ascendancesM %}
                     {% for enfant in question.question_set.all %}
                        {% if forloop.counter == 1 %}
                            <tr style="display: none;" class="child-row-{{question.parent_id}}{{question.relation}}{{question.cible}}">
                                {% include "gh_snippet.html" with typequest=question.typequestion textequest=question.questionen questid=question.id persid=pid province=user.profile.province relation=enfant.relation cible=enfant.cible classe="fillemere" varname=question.varname intid=intid %}
                                {% include "aidegh_snippet.html" with aide=question.aideen classe="fillemere" %}
                            </tr>
                        {% endif %}
                     {% endfor %}
            {% elif question.id in ascendancesM and question.id not in ascendancesF %}
                <tr class="mere">
                    {% for enfant in question.question_set.all %}
                        {% if forloop.counter == 1 %}
                            {% include "gh_snippet.html" with typequest=question.typequestion textequest=question.questionen questid=question.id persid=pid  province=user.profile.province relation=enfant.relation cible=enfant.cible classe="mere" varname=question.varname  intid=intid %}
                            {% include "aidegh_snippet.html" with aide=question.aideen %}
                </tr>
                        {% endif %}
                     {% endfor %}
            {% endif %}
            {% for enfant in question.question_set.all %}
                {% if enfant.id not in ascendancesM %}
                     <tr style="display: none;" class="child-row-{{enfant.parent_id}}{{enfant.relation}}{{enfant.cible}}">
                     {% if enfant.id|divisibleby:2 %}
                         {% include "gh_snippet.html" with typequest=enfant.typequestion textequest=enfant.questionen questid=enfant.id persid=pid province=user.profile.province classe="fifille" varname=enfant.varname  intid=intid %}
                         {% include "aidegh_snippet.html" with aide=enfant.aideen classe="fifille" %}
                    {% else %}
                         {% include "gh_snippet.html" with typequest=enfant.typequestion textequest=enfant.questionen questid=enfant.id persid=pid province=user.profile.province classe="fille" varname=enfant.varname  intid=intid %}
                         {% include "aidegh_snippet.html" with aide=enfant.aideen classe="fille" %}
                    {% endif %}
                     </tr>
                 {% endif %}
            {% endfor %}
        {% endif %}
    {% endfor %}
</table>

</div><!--Fermeture de la boite à onglets-->
{% endblock content %}

templates/saveinstrugh.html
{% extends 'gh_base.html' %}
{% load i18n %}
{% load static %}
{% load formulairesgh %}

{% block content %}
<h2> {{ code }} - {{ questionnaire }} - {{ interview }}</h2>
{% csrf_token %}
   <input name="pid" type="hidden" value="{{ pid }}" />
   <input name="qid" type="hidden" value="{{ qid }}" />
   <input name="intid" type="hidden" value="{{ intid }}" />

   <p class="termine">{% include "gh_snippet.html" with typequest=questionfin.typequestion textequest=questionfin.questionen questid=questionfin.id persid=pid province=user.profile.province varname=questionfin.varname intid=intid %}</p>
   <div class="tabber">
    {% for instrument in instruments %}
        {% if forloop.counter > 1 %}
        </table></div>
        {% endif %}
        <div class="tabbertab"><h3>{{ instrument.nom.questionen|slice:"0:15" }}</h3><b>{{ instrument.nom }}</b>
        <table>
        <tr><td></td><td></td><td></td></tr>
        {% for question in instrument.iteminstrument_set.all|dictsort:"question.questionno" %}
           {% if question.question.phase != "0" %}

            {% if question.questionitem_set.all.exists %}
                <tr class="{% cycle 'Q1' 'Q2' %}"><td class="{% cycle 'Q1' 'Q2' %}"><a href="javascript:basculer({{question.question.id }}, 10000, 10);"><b>Data</b></a></td>
            {% else %}
                <tr class="{% cycle 'Q1' 'Q2' %}"><td class="{% cycle 'Q1' 'Q2' %}"></td>
            {% endif %}
                 {% include "gh_snippet.html" with typequest=question.question.typequestion textequest=question.question.questionen questid=question.question.id persid=pid province=user.profile.province varname=question.question.varname intid=intid %}
                 {% include "aidegh_snippet.html" with aide=question.question.aideen %}

             </tr>
            {% endif %}
            <tr><td colspan=4 >
            <table class="fille" id="A10_{{ question.question.id }}" style="display: none;">
            {% for liee in question.questionitem_set.all %}
                <tr class="fille"><td class="fille">
                    {% include "gh_lieesnippet.html" with typequest=liee.question.typequestion textequest=liee.question.questionen questid=liee.question.id persid=pid province=user.profile.province intid=intid %}
                </td></tr>
            {% endfor %}

             </table>
            </td></tr>

        {% endfor %}
    {% endfor %}
</table>

</div><!--Fermeture de la boite à onglets-->
{% endblock content %}